training:
  lr: 0.01
  weight-decay: 0.0001
  bs: 2 #32
  val_bs: 2 #32
  optimizer: 'SGD'
  scheduler: 'cosinelr' 
  gamma: 0.1
  step-size: 5
  augmentation: 'max' # min/max

test:
  bs: 1

model:
  image-size: 224
  patch-size: 1
  num-classes: 1
  num-patches: 49
  num-frames: 8
  max-identities: 2
  dim: 256
  depth: 4 # 9 v2 3 v3
  dim-head: 64
  channels: 2048 # Xception: 2048 | EfficientNet: 1280
  heads: 4
  attn-dropout: 0.
  ff-dropout: 0.
  shift-tokens: False
  enable-size-emb: True
  enable-pos-emb: True
  enable-identity-attention: True
